"""add agent_traces table

Revision ID: e6083f5206e8
Revises: f4b5e16baaa8
Create Date: 2026-07-03 04:30:49.360711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6083f5206e8'
down_revision: Union[str, None] = 'f4b5e16baaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_type', sa.Enum('incident', 'security_alert', name='tracesubjecttype'), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_subject_id'), 'agent_traces', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_traces_subject_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
